namespace DesignAgent.Server.Models.DesignIntelligence;

/// <summary>
/// Represents a complete captured design from a website (multiple pages analyzed)
/// </summary>
public class CapturedDesign
{
    /// <summary>
    /// Unique identifier for this design
    /// </summary>
    public string Id { get; set; } = Guid.NewGuid().ToString();
    
    /// <summary>
    /// Source URL (e.g., "https://linear.app")
    /// </summary>
    public required string Url { get; set; }
    
    /// <summary>
    /// User-provided or auto-generated name for this design
    /// </summary>
    public string? Name { get; set; }
    
    /// <summary>
    /// Auto-generated name from LLM (e.g., "Gradient Excellence", "Minimal SaaS")
    /// </summary>
    public string? AutoGeneratedName { get; set; }
    
    /// <summary>
    /// When this design was captured
    /// </summary>
    public DateTime CapturedAt { get; set; } = DateTime.UtcNow;
    
    /// <summary>
    /// Individual page analyses (homepage, pricing, features, etc.)
    /// </summary>
    public List<PageAnalysis> Pages { get; set; } = new();
    
    /// <summary>
    /// Overall site score (weighted average of page scores)
    /// </summary>
    public double OverallScore { get; set; }
    
    /// <summary>
    /// Design DNA - unified profile of the site's design philosophy
    /// </summary>
    public DesignDNA? DesignDNA { get; set; }
    
    /// <summary>
    /// Detected design system (if any)
    /// </summary>
    public DetectedDesignSystem? DetectedSystem { get; set; }
    
    /// <summary>
    /// Whether this design passed the quality gate
    /// </summary>
    public bool PassedQualityGate { get; set; }
    
    /// <summary>
    /// Current rank in leaderboard (1-100, null if not in leaderboard)
    /// </summary>
    public int? LeaderboardRank { get; set; }
    
    /// <summary>
    /// Tags extracted from all pages
    /// </summary>
    public List<string> Tags { get; set; } = new();
    
    /// <summary>
    /// Human feedback rating (1-5, where 1=thumbs down, 5=thumbs up)
    /// </summary>
    public int? HumanRating { get; set; }
    
    /// <summary>
    /// Human feedback timestamp
    /// </summary>
    public DateTime? HumanRatedAt { get; set; }
    
    /// <summary>
    /// Extracted design patterns from this site
    /// </summary>
    public List<string> ExtractedPatternIds { get; set; } = new();
}

/// <summary>
/// Unified design profile capturing overall style and philosophy
/// </summary>
public class DesignDNA
{
    /// <summary>
    /// Overall design philosophy (e.g., "minimal", "maximalist", "brutalist")
    /// </summary>
    public string Philosophy { get; set; } = string.Empty;
    
    /// <summary>
    /// Color philosophy (e.g., "vibrant gradients", "muted pastels", "bold primaries")
    /// </summary>
    public string ColorPhilosophy { get; set; } = string.Empty;
    
    /// <summary>
    /// Typography approach (e.g., "large serif headings with sans body", "monospace technical")
    /// </summary>
    public string TypographyStyle { get; set; } = string.Empty;
    
    /// <summary>
    /// Spacing philosophy (e.g., "generous whitespace", "compact efficient", "dramatic scale")
    /// </summary>
    public string SpacingStyle { get; set; } = string.Empty;
    
    /// <summary>
    /// Interaction style (e.g., "subtle micro-interactions", "bold animations", "minimal hover states")
    /// </summary>
    public string InteractionStyle { get; set; } = string.Empty;
    
    /// <summary>
    /// Target audience perception (e.g., "enterprise", "consumer", "developer", "creative")
    /// </summary>
    public string TargetAudience { get; set; } = string.Empty;
    
    /// <summary>
    /// Standout elements that make this design unique
    /// </summary>
    public List<string> StandoutElements { get; set; } = new();
}

/// <summary>
/// Information about detected design system or framework
/// </summary>
public class DetectedDesignSystem
{
    /// <summary>
    /// Framework name (e.g., "Tailwind", "Bootstrap", "Material UI", "Custom")
    /// </summary>
    public string Framework { get; set; } = string.Empty;
    
    /// <summary>
    /// Component library (e.g., "shadcn/ui", "Radix UI", "Chakra UI", "None")
    /// </summary>
    public string? ComponentLibrary { get; set; }
    
    /// <summary>
    /// Whether this is a custom design system
    /// </summary>
    public bool IsCustomSystem { get; set; }
    
    /// <summary>
    /// Design system maturity (0-10)
    /// </summary>
    public double SystemMaturity { get; set; }
    
    /// <summary>
    /// Evidence of design system (e.g., "Consistent spacing scale", "Design tokens in CSS")
    /// </summary>
    public List<string> Evidence { get; set; } = new();
}

